rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  # joint1_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: joint1
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint2_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: joint2
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # Joint Trajectory Controllers -------------------------------
  rrbot_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
    gains:
      joint1: {p: 300.0, i: 0.003, d: 60.0}
      joint2: {p: 300.0, i: 0.003, d: 60.0}
